services:
  astro-app:
    build: .
    container_name: hacktoberfestGye
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm dev --host 0.0.0.0 --port 4321
